require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/coverdetails", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Coverdetail. As you add validations to Coverdetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Coverdetail.create! valid_attributes
      get coverdetails_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      coverdetail = Coverdetail.create! valid_attributes
      get coverdetail_url(coverdetail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_coverdetail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      coverdetail = Coverdetail.create! valid_attributes
      get edit_coverdetail_url(coverdetail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Coverdetail" do
        expect {
          post coverdetails_url, params: { coverdetail: valid_attributes }
        }.to change(Coverdetail, :count).by(1)
      end

      it "redirects to the created coverdetail" do
        post coverdetails_url, params: { coverdetail: valid_attributes }
        expect(response).to redirect_to(coverdetail_url(Coverdetail.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Coverdetail" do
        expect {
          post coverdetails_url, params: { coverdetail: invalid_attributes }
        }.to change(Coverdetail, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post coverdetails_url, params: { coverdetail: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested coverdetail" do
        coverdetail = Coverdetail.create! valid_attributes
        patch coverdetail_url(coverdetail), params: { coverdetail: new_attributes }
        coverdetail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the coverdetail" do
        coverdetail = Coverdetail.create! valid_attributes
        patch coverdetail_url(coverdetail), params: { coverdetail: new_attributes }
        coverdetail.reload
        expect(response).to redirect_to(coverdetail_url(coverdetail))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        coverdetail = Coverdetail.create! valid_attributes
        patch coverdetail_url(coverdetail), params: { coverdetail: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested coverdetail" do
      coverdetail = Coverdetail.create! valid_attributes
      expect {
        delete coverdetail_url(coverdetail)
      }.to change(Coverdetail, :count).by(-1)
    end

    it "redirects to the coverdetails list" do
      coverdetail = Coverdetail.create! valid_attributes
      delete coverdetail_url(coverdetail)
      expect(response).to redirect_to(coverdetails_url)
    end
  end
end
